-- MySQL Script generated by MySQL Workbench
-- 08/06/17 20:36:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fgv3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fgv3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fgv3` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `fgv3` ;



-- -----------------------------------------------------
-- Table `fgv3`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fgv3`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(100) NULL COMMENT '',
  `email` VARCHAR(100) NULL COMMENT '',
  `senha` VARCHAR(100) NULL COMMENT '',
  `setor` VARCHAR(45) NULL COMMENT '',
  `tipo` VARCHAR(45) NULL COMMENT '',
  `datacadas` DATE NULL COMMENT '',
  `acesso` INT(11) NULL COMMENT '',
  `color_user` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idusuarios`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fgv3`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fgv3`.`categoria` (
  `categoria_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `categoria_nome` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`categoria_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fgv3`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fgv3`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(200) NULL COMMENT '',
  `descricao` VARCHAR(200) NULL COMMENT '',
  `color` VARCHAR(100) NULL COMMENT '',
  `start` DATETIME NULL COMMENT '',
  `end` DATETIME NULL COMMENT '',
  `usuarios_idusuarios` INT NOT NULL COMMENT '',
  `categoria_categoria_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_events_usuarios_idx` (`usuarios_idusuarios` ASC)  COMMENT '',
  INDEX `fk_events_categoria1_idx` (`categoria_categoria_id` ASC)  COMMENT '',
  CONSTRAINT `fk_events_usuarios`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `fgv3`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_categoria1`
    FOREIGN KEY (`categoria_categoria_id`)
    REFERENCES `fgv3`.`categoria` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fgv3`.`usersonline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fgv3`.`usersonline` (
  `ip` VARCHAR(255) NOT NULL COMMENT '',
  `usersonlinecol` INT(10) NULL COMMENT '',
  `usersonlinecol1` VARCHAR(45) NULL COMMENT '')
ENGINE = InnoDB
COMMENT = '     ';


-- -----------------------------------------------------
-- Table `fgv3`.`viagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fgv3`.`viagens` (
  `viagens_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `viagens_cidade` VARCHAR(200) NULL COMMENT '',
  `viagens_dias` VARCHAR(200) NULL COMMENT '',
  `viagens_empresa` VARCHAR(200) NULL COMMENT '',
  `rotinaexterna_externaid` INT NOT NULL COMMENT '',
  `events_id` INT NOT NULL COMMENT '',
  `categoria_id` INT NULL COMMENT '',
  PRIMARY KEY (`viagens_id`)  COMMENT '',
  INDEX `fk_viagens_events1_idx` (`events_id` ASC)  COMMENT '',
  INDEX `fk_viagens_events2_idx` (`categoria_id` ASC)  COMMENT '',
  CONSTRAINT `fk_events_categoria2`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `fgv3`.`events` (`categoria_categoria_id`)
    ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagens_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `fgv3`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fgv3`.`visitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fgv3`.`visitas` (
  `visitas_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `visitas_cidade` VARCHAR(45) NULL COMMENT '',
  `visitas_estado` VARCHAR(45) NULL COMMENT '',
  `visita_agendamento` VARCHAR(45) NULL COMMENT '',
  `rotinaexterna_externaid` INT NOT NULL COMMENT '',
  `events_id` INT NOT NULL COMMENT '',
  `categoria_id` INT NULL COMMENT '',
  PRIMARY KEY (`visitas_id`)  COMMENT '',
  INDEX `fk_visitas_events1_idx` (`events_id` ASC)  COMMENT '',
  INDEX `fk_viagens_events2_idx` (`categoria_id` ASC)  COMMENT '',
  CONSTRAINT `fk_events_categoria3`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `fgv3`.`events` (`categoria_categoria_id`)
    ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `fk_visitas_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `fgv3`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fgv3`.`sazonais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fgv3`.`sazonais` (
  `sazonais_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `sazonais_data` DATE NULL COMMENT '',
  `sazonais_desc` VARCHAR(255) NULL COMMENT '',
  `estrategia_idestrategia` INT NOT NULL COMMENT '',
  `events_id` INT NOT NULL COMMENT '',
  `categoria_id` INT NULL COMMENT '',
  PRIMARY KEY (`sazonais_id`)  COMMENT '',
  INDEX `fk_sazonais_events1_idx` (`events_id` ASC)  COMMENT '',
  INDEX `fk_viagens_events2_idx` (`categoria_id` ASC)  COMMENT '',
  CONSTRAINT `fk_events_categoria4`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `fgv3`.`events` (`categoria_categoria_id`)
    ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `fk_sazonais_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `fgv3`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fgv3`.`participaevento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fgv3`.`participaevento` (
  `part_evento_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `part_evento_data` DATE NULL COMMENT '',
  `part_evento_desc` VARCHAR(255) NULL COMMENT '',
  `estrategia_idestrategia` INT NOT NULL COMMENT '',
  `events_id` INT NOT NULL COMMENT '',
  `categoria_id` INT NULL COMMENT '',
  PRIMARY KEY (`part_evento_id`)  COMMENT '',
  INDEX `fk_participaevento_events1_idx` (`events_id` ASC)  COMMENT '',
  INDEX `fk_viagens_events2_idx` (`categoria_id` ASC)  COMMENT '',
  CONSTRAINT `fk_events_categoria5`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `fgv3`.`events` (`categoria_categoria_id`)
    ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `fk_participaevento_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `fgv3`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fgv3`.`campanhapub`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fgv3`.`campanhapub` (
  `campanhapub_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `campanhapub_data` DATE NULL COMMENT '',
  `campanhapub_desc` VARCHAR(255) NULL COMMENT '',
  `estrategia_idestrategia` INT NOT NULL COMMENT '',
  `events_id` INT NOT NULL COMMENT '',
  `categoria_id` INT NULL COMMENT '',
  PRIMARY KEY (`campanhapub_id`)  COMMENT '',
  INDEX `fk_campanhapub_events1_idx` (`events_id` ASC)  COMMENT '',
  INDEX `fk_viagens_events2_idx` (`categoria_id` ASC)  COMMENT '',
  CONSTRAINT `fk_events_categoria6`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `fgv3`.`events` (`categoria_categoria_id`)
    ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `fk_campanhapub_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `fgv3`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fgv3`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fgv3`.`materias` (
  `materiais_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `materiais_tipo` VARCHAR(45) NULL COMMENT '',
  `materias_data` DATE NULL COMMENT '',
  `rotinaexterna_externa_id` INT NOT NULL COMMENT '',
  `events_id` INT NOT NULL COMMENT '',
  `categoria_id` INT NULL COMMENT '',
  PRIMARY KEY (`materiais_id`)  COMMENT '',
  INDEX `fk_materias_events1_idx` (`events_id` ASC)  COMMENT '',
  INDEX `fk_viagens_events2_idx` (`categoria_id` ASC)  COMMENT '',
  CONSTRAINT `fk_events_categoria7`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `fgv3`.`events` (`categoria_categoria_id`)
    ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `fk_materias_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `fgv3`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fgv3`.`contatocliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fgv3`.`contatocliente` (
  `contatocliente_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `contatocliente_tipo` VARCHAR(255) NULL COMMENT '',
  `contatoclientecol` VARCHAR(45) NULL COMMENT '',
  `rotinainterna_interna_id` INT NOT NULL COMMENT '',
  `events_id` INT NOT NULL COMMENT '',
  `categoria_id` INT NULL COMMENT '',
  PRIMARY KEY (`contatocliente_id`)  COMMENT '',
  INDEX `fk_contatocliente_events1_idx` (`events_id` ASC)  COMMENT '',
  INDEX `fk_viagens_events2_idx` (`categoria_id` ASC)  COMMENT '',
  CONSTRAINT `fk_events_categoria8`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `fgv3`.`events` (`categoria_categoria_id`)
    ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `fk_contatocliente_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `fgv3`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fgv3`.`negociacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fgv3`.`negociacao` (
  `negociacao_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `negociacao_desc` VARCHAR(255) NULL COMMENT '',
  `rotinainterna_interna_id` INT NOT NULL COMMENT '',
  `categoria_categoria_id` INT NOT NULL COMMENT '',
  `events_id` INT NOT NULL COMMENT '',
  `categoria_id` INT NULL COMMENT '',
  PRIMARY KEY (`negociacao_id`)  COMMENT '',
  INDEX `fk_negociacao_events1_idx` (`events_id` ASC)  COMMENT '',
  INDEX `fk_viagens_events2_idx` (`categoria_id` ASC)  COMMENT '',
  CONSTRAINT `fk_events_categoria9`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `fgv3`.`events` (`categoria_categoria_id`)
    ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `fk_negociacao_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `fgv3`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = ' ';


-- -----------------------------------------------------
-- Table `fgv3`.`sge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fgv3`.`sge` (
  `sge_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `sge_desc` VARCHAR(255) NULL COMMENT '',
  `rotinainterna_interna_id` INT NOT NULL COMMENT '',
  `events_id` INT NOT NULL COMMENT '',
  `categoria_id` INT NULL COMMENT '',
  PRIMARY KEY (`sge_id`)  COMMENT '',
  INDEX `fk_sge_events1_idx` (`events_id` ASC)  COMMENT '',
  INDEX `fk_viagens_events2_idx` (`categoria_id` ASC)  COMMENT '',
  CONSTRAINT `fk_events_categoria10`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `fgv3`.`events` (`categoria_categoria_id`)
    ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `fk_sge_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `fgv3`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fgv3`.`atualizarcadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fgv3`.`atualizarcadas` (
  `atualizarcadas_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `atualizarcadas_desc` VARCHAR(255) NULL COMMENT '',
  `rotinainterna_interna_id` INT NOT NULL COMMENT '',
  `events_id` INT NOT NULL COMMENT '',
  `categoria_id` INT NULL COMMENT '',
  PRIMARY KEY (`atualizarcadas_id`)  COMMENT '',
  INDEX `fk_atualizarcadas_events1_idx` (`events_id` ASC)  COMMENT '',
  INDEX `fk_viagens_events2_idx` (`categoria_id` ASC)  COMMENT '',
  CONSTRAINT `fk_events_categoria11`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `fgv3`.`events` (`categoria_categoria_id`)
    ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `fk_atualizarcadas_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `fgv3`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fgv3`.`posvenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fgv3`.`posvenda` (
  `posvenda_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `posvenda_desc` VARCHAR(255) NULL COMMENT '',
  `rotinainterna_interna_id` INT NOT NULL COMMENT '',
  `events_id` INT NOT NULL COMMENT '',
  `categoria_id` INT NULL COMMENT '',
  PRIMARY KEY (`posvenda_id`)  COMMENT '',
  INDEX `fk_posvenda_events1_idx` (`events_id` ASC)  COMMENT '',
  INDEX `fk_viagens_events2_idx` (`categoria_id` ASC)  COMMENT '',
  CONSTRAINT `fk_events_categoria12`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `fgv3`.`events` (`categoria_categoria_id`)
    ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `fk_posvenda_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `fgv3`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

--
-- Estrutura da tabela `cursos`
--

CREATE TABLE IF NOT EXISTS `cursos` (
  `cursos_id` int(11) NOT NULL,
  `cursos_nome` varchar(100) NOT NULL,
  `cursos_cargahoraria` int(11) NOT NULL,
  `cursos_valor` varchar(100) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `cursos`
--

INSERT INTO `cursos` (`cursos_id`, `cursos_nome`, `cursos_cargahoraria`, `cursos_valor`) VALUES
(2, 'MBA EM GESTÃƒO COMERCIAL', 0, '0'),
(3, 'MBA EM GESTÃƒO EMPRESARIAL', 0, '0'),
(4, 'MBA EM GESTÃƒO ESTRATÃ‰GICA DE PESSOAS', 0, '0'),
(5, 'MBA EM GESTÃƒO FINANCEIRA: CONTROLADORIA E AUDITORIA', 0, '0'),
(6, 'MBA EM GESTÃƒO: INDUSTRIAL', 0, '0'),
(7, 'MBA EM GESTÃƒO: MARKETING', 0, '0'),
(8, 'MBA EM GESTÃƒO: PESSOAS E LIDERANÃ‡A', 0, '0'),
(9, 'MBA EM GESTÃƒO: PROJETOS', 0, '0'),
(10, 'MBA EM MARKETING: ÃŠNFASE EM VENDAS', 0, '0'),
(11, 'MBA EXECUTIVO EM ECONOMIA E GESTÃƒO: AGRONEGÃ“CIO', 0, '0'),
(12, 'MBA GESTÃƒO: COMERCIAL', 0, '0'),
(13, 'MBA GESTÃƒO: FINANCEIRA, CONTROLADORIA E AUDITORIA', 0, '0'),
(14, 'LL.M EM DIREITO: EMPRESARIAL', 0, '0'),
(15, 'PÃ“S-GRADUAÃ‡ÃƒO EM ADMINISTRAÃ‡ÃƒO DE EMPRESAS', 0, '0'),
(16, 'MBA EM DIREITO TRIBUTÃRIO', 120, '15.000,00');

-- --------------------------------------------------------

INSERT INTO `usuarios` (`idusuarios`, `nome`, `email`, `senha`, `setor`, `tipo`, `datacadas`, `acesso`, `color_user`) VALUES
(1, 'ADM', 'adm@adm.com.br', '!@#1234', 'Administrativo', 'ADM', '2017-08-04', 13, '#4169E1'),
(23747, 'Fabricia', 'fabricia.fgv@mebbrasil.com.br', '!@#1234', 'Vendas', 'usuario_comum', '2017-07-31', 4, '#00CED1'),
(219803, 'Bruna', 'bruna.fgv@mebbrasil.com.br', '!@#1234', 'Vendas', 'ADM', '2017-07-31', 4, '#3CB371'),
(220414, 'Catiuscia', 'catiuscia.fgv@mebbrasil.com.br', '!@#1234', 'Vendas', 'ADM', '2017-07-31', 1, '#FFD700'),
(367463, 'Daniela', 'daniela.fgv@mebbrasil.com.br', '!@#1234', 'Vendas', 'usuario_comum', '2017-07-31', 3, '#D2691E'),
(541244, 'Aline', 'aline.fgv@mebbrasil.com.br', '!@#1234', 'Vendas', 'usuario_comum', '2017-07-31', NULL, '#FF6347'),
(689117, 'Ivania', 'Ivania.fgv@mebbrasil.com.br', '!@#1234', 'Vendas', 'usuario_comum', '2017-07-31', NULL, '#ccdde5');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
